name: '(Reusable) GitHub Release to Linear'

on:
  workflow_call:
    secrets:
      linear-api-key:
        description: 'The Linear API key.'
        required: true

jobs:
  update-linear-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous release tag
        id: previous_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 2
            });

            if (releases.data.length < 2) {
              core.info('No previous release found.');
              return;
            }
            const previousRelease = releases.data[1];
            core.setOutput('tag_name', previousRelease.tag_name);

      - name: Get PR numbers in release
        id: pr_numbers
        if: steps.previous_release.outputs.tag_name
        run: |
          prev_tag=${{ steps.previous_release.outputs.tag_name }}
          current_tag=${{ github.ref_name }}
          pr_numbers_json=$(git log $prev_tag..$current_tag --pretty=%s | grep -oE '\(#[0-9]+\)' | grep -oE '[0-9]+' | jq -scR 'split("\n") | map(select(length > 0)) | map(tonumber)')
          echo "numbers=${pr_numbers_json}" >> $GITHUB_OUTPUT

      - name: Find and update Linear tickets
        if: steps.pr_numbers.outputs.numbers && steps.pr_numbers.outputs.numbers != '[]'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumbers = ${{ steps.pr_numbers.outputs.numbers }};
            const linearApiKey = '${{ secrets.linear-api-key }}';

            const PLATFORM_TICKET_PATTERN = /PLAT-\d+/g;
            const CORE_TICKET_PATTERN = /CORE-\d+/g;
            const TEAMS_STATES_MAP = {
              platform: {
                merged: '1ee53a4e-8e7b-487b-a023-08d09729da98', // "🔀 Merged" state ID from Team Platform
                released: '0b5181e6-b7a0-4b4b-b441-ada23e377579', // Team Platform "🚀 Released" status ID
              },
              core: {
                merged: '1ee53a4e-8e7b-487b-a023-08d09729da98', // TBD
                released: '5f5062ff-23a2-48dc-8541-dea69385f943', // Team Core "🚀 Released" status ID
              },
            };

            if (!prNumbers || prNumbers.length === 0) {
              core.info('No PRs found in this release.');
              return;
            }

            async function linearQuery(query, variables) {
              const response = await fetch('https://api.linear.app/graphql', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  'Authorization': linearApiKey,
                },
                body: JSON.stringify({ query, variables }),
              });
              const result = await response.json();
              if (result.errors) {
                throw new Error(`Linear API Error: ${JSON.stringify(result.errors)}`);
              }
              return result.data;
            }

            const platformTicketIdentifiers = new Set();
            const coreTicketIdentifiers = new Set();

            const prPromises = prNumbers.map(prNumber =>
              github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              })
            );

            const prResults = await Promise.allSettled(prPromises);

            prResults.forEach((result, index) => {
              if (result.status === 'fulfilled') {
                const pr = result.value.data;
                const content = `${pr.title} ${pr.body || ''} ${pr.head.ref}`;

                for (const match of content.matchAll(PLATFORM_TICKET_PATTERN)) {
                  platformTicketIdentifiers.add(match[0]);
                }
                for (const match of content.matchAll(CORE_TICKET_PATTERN)) {
                  coreTicketIdentifiers.add(match[0]);
                }
              } else {
                const prNumber = prNumbers[index];
                core.warning(`Could not fetch PR #${prNumber}. It might have been deleted. Error: ${result.reason.message}`);
              }
            });

            if (platformTicketIdentifiers.size === 0 && coreTicketIdentifiers.size === 0) {
              core.info('No Linear tickets for Team Platform or Team Core found in release PRs.');
              return;
            }

            async function updateTickets(ticketIdentifiers, stateId, teamName) {
              if (ticketIdentifiers.size === 0) {
                return;
              }
              core.info(`Found ${teamName} tickets: ${Array.from(ticketIdentifiers).join(', ')}`);

              const getIssuesQuery = `
                query GetIssuesByState($stateIds: [ID!]) {
                  issues(first: 250, filter: { state: { id: { in: $stateIds } } }) {
                    nodes {
                      identifier
                    }
                  }
                }`;

              const issuesResponse = await linearQuery(getIssuesQuery, { stateIds: [TEAMS_STATES_MAP.platform.merged] });

              const issuesInRequiredState = new Set(issuesResponse.issues.nodes.map(issue => issue.identifier));
              const ticketsToUpdate = Array.from(ticketIdentifiers).filter(ticketIdentifier => issuesInRequiredState.has(ticketIdentifier));

              if (ticketsToUpdate.length === 0) {
                core.info(`No ${teamName} tickets were in the required state to be moved.`);
                return;
              }

              core.info(`Found ${teamName} tickets to update: ${ticketsToUpdate.join(', ')}`);

              const updatePromises = ticketsToUpdate.map(ticketIdentifier => {
                core.info(`Updating ${teamName} ticket ${ticketIdentifier} to state ${stateId}`);
                const updateQuery = `
                  mutation UpdateIssueStatus($issueId: String!, $stateId: String!) {
                    issueUpdate(id: $issueId, input: { stateId: $stateId }) {
                      success
                      issue {
                        id
                        state {
                          id
                          name
                        }
                      }
                    }
                  }`;
                return linearQuery(updateQuery, { issueId: ticketIdentifier, stateId: stateId });
              });

              const updateResults = await Promise.allSettled(updatePromises);

              updateResults.forEach((result, index) => {
                const ticketIdentifier = ticketsToUpdate[index];
                if (result.status === 'fulfilled') {
                  const updateResult = result.value;
                  if (updateResult.issueUpdate.success) {
                    core.info(`Successfully updated ticket ${ticketIdentifier} to state "${updateResult.issueUpdate.issue.state.name}".`);
                  } else {
                    core.error(`Failed to update ticket ${ticketIdentifier}, success was false.`);
                  }
                } else {
                  core.error(`Error processing ticket ${ticketIdentifier}: ${result.reason.message}`);
                }
              });
            }

            await Promise.all([
              updateTickets(platformTicketIdentifiers, TEAMS_STATES_MAP.platform.released, 'Team Platform'),
              updateTickets(coreTicketIdentifiers, TEAMS_STATES_MAP.core.released, 'Team Core')
            ]);
